export const ENDPOINTS = {
  AUTH: {
    REGISTER: '/api/v1/auth/register',
    LOGIN: '/api/v1/auth/login',
    LOGOUT: '/api/v1/auth/logout',
    REFRESH: '/api/v1/auth/refresh',
    CSRF_TOKEN: '/api/v1/auth/csrf-token',
    ME: '/api/v1/auth/me',
    VERIFY_EMAIL: '/api/v1/auth/verify-email',
    RESEND_VERIFICATION: '/api/v1/auth/resend-verification',
    FORGOT_PASSWORD: '/api/v1/auth/forgot-password',
    RESET_PASSWORD: '/api/v1/auth/reset-password',
    GOOGLE: '/api/v1/auth/google',
    FACEBOOK: '/api/v1/auth/facebook',
  },
  USERS: {
    PROFILE: '/api/v1/users/profile',
    PASSWORD: '/api/v1/users/password',
    FORCE_CHANGE_PASSWORD: '/api/v1/users/password/force-change',
    SETTINGS: '/api/v1/users/settings',
    API_TOKENS: '/api/v1/users/api-tokens',
  },
  CONTACTS: {
    BASE: '/api/v1/contacts',
    TAGS: '/api/v1/contacts/tags',
    TAGS_BULK_ASSIGN: '/api/v1/contacts/tags/bulk-assign',
    GROUPS: '/api/v1/contacts/groups',
    GROUPS_BULK_MEMBERSHIPS: '/api/v1/contacts/groups/bulk-memberships',
    BULK_DELETE: '/api/v1/contacts/bulk-delete',
    IMPORT_CSV: '/api/v1/contacts/import/csv',
    IMPORT_GROUPS_CSV: '/api/v1/contacts/groups/import/csv',
    SAMPLE_CONTACT_CSV: '/api/v1/contacts/import/csv/sample/contacts',
    SAMPLE_GROUP_CSV: '/api/v1/contacts/import/csv/sample/groups',
  },
  TEMPLATES: {
    BASE: '/api/v1/templates',
    SYNC: '/api/v1/templates/sync',
  },
  FLOWS: {
    BASE: '/api/v1/flows',
    SYNC: '/api/v1/flows/sync',
    DATA_EXCHANGE: '/api/v1/flows/data-exchange',
    REFRESH_PREVIEW: (id: string) => `/api/v1/flows/${id}/refresh-preview`,
  },
  CAMPAIGNS: {
    BASE: '/api/v1/campaigns',
  },
  CHAT: {
    CONVERSATIONS: '/api/v1/chat/conversations',
  },
  WHATSAPP: {
    ACCOUNTS: '/api/v1/whatsapp/accounts',
    EMBEDDED_SIGNUP_PREVIEW: '/api/v1/whatsapp/accounts/embedded-signup/preview',
    EMBEDDED_SIGNUP: '/api/v1/whatsapp/accounts/embedded-signup',
    ACCOUNT_HEALTH: (id: string) => `/api/v1/whatsapp/accounts/${id}/health`,
    ACCOUNT_RECONCILE: (id: string) => `/api/v1/whatsapp/accounts/${id}/reconcile`,
    SEND: '/api/v1/whatsapp/send',
    SEND_TEMPLATE: '/api/v1/whatsapp/send/template',
    SEND_FLOW: '/api/v1/whatsapp/send/flow',
    MESSAGES: '/api/v1/whatsapp/messages',
  },
  AUTOMATIONS: {
    BASE: '/api/v1/automations',
    WEBHOOKS: '/api/v1/automations/webhooks',
  },
  ORGANIZATIONS: {
    BASE: '/api/v1/organizations',
    ME: '/api/v1/organizations/me',
    ACCEPT_INVITATION: '/api/v1/organizations/invitations/accept',
    MEMBERS: (id: string) => `/api/v1/organizations/${id}/members`,
    CREATE_MEMBER_ACCOUNT: (id: string) => `/api/v1/organizations/${id}/members/create-account`,
    INVITATIONS: (id: string) => `/api/v1/organizations/${id}/invitations`,
    RESEND_INVITATION: (id: string, invitationId: string) =>
      `/api/v1/organizations/${id}/invitations/${invitationId}/resend`,
    REVOKE_INVITATION: (id: string, invitationId: string) =>
      `/api/v1/organizations/${id}/invitations/${invitationId}/revoke`,
    DELETE_INVITATION: (id: string, invitationId: string) =>
      `/api/v1/organizations/${id}/invitations/${invitationId}`,
  },
  SUBSCRIPTIONS: {
    PLANS: '/api/v1/subscriptions/plans',
    PLAN_DETAILS: (slug: string) => `/api/v1/subscriptions/plans/${slug}`,
    SUBSCRIBE: '/api/v1/subscriptions/subscribe',
    CHANGE_PLAN: '/api/v1/subscriptions/change-plan',
    VERIFY_PAYMENT: '/api/v1/subscriptions/verify-payment',
    CURRENT: '/api/v1/subscriptions/current',
    AUTO_RENEW: '/api/v1/subscriptions/current/auto-renew',
    CANCEL: '/api/v1/subscriptions/cancel',
    VALIDATE_COUPON: '/api/v1/subscriptions/coupons/validate',
    HISTORY: '/api/v1/subscriptions/history',
  },
  WALLET: {
    BASE: '/api/v1/wallet',
    RECHARGE: '/api/v1/wallet/recharge',
    VERIFY_RECHARGE: '/api/v1/wallet/recharge/verify',
    TRANSACTIONS: '/api/v1/wallet/transactions',
    INVOICES: '/api/v1/wallet/invoices',
  },
  NOTIFICATIONS: {
    BASE: '/api/v1/notifications',
    UNREAD_COUNT: '/api/v1/notifications/unread-count',
    READ_ALL: '/api/v1/notifications/read-all',
  },
  SUPPORT: {
    TICKETS: '/api/v1/support/tickets',
    UNREAD_COUNT: '/api/v1/support/tickets/unread-count',
    TICKET_DETAIL: (id: string) => `/api/v1/support/tickets/${id}`,
    TICKET_MESSAGES: (id: string) => `/api/v1/support/tickets/${id}/messages`,
    TICKET_READ: (id: string) => `/api/v1/support/tickets/${id}/read`,
  },
  ANALYTICS: {
    DASHBOARD: '/api/v1/analytics/dashboard',
    METRICS: '/api/v1/analytics/metrics',
  },
  MEDIA: {
    UPLOAD: '/api/v1/media/upload',
    BASE: '/api/v1/media',
  },
  SETTINGS: {
    PUBLIC: '/api/v1/settings/public',
  },
  ADMIN: {
    AUTHORIZATION: '/api/v1/admin/me/authorization',
    INVITATION_VALIDATE: '/api/v1/admin/invitations/validate',
    INVITATION_ACCEPT: '/api/v1/admin/invitations/accept',
    DASHBOARD: '/api/v1/admin/analytics/dashboard',
    METRICS: '/api/v1/admin/analytics/metrics',
    USERS: '/api/v1/admin/users',
    PLANS: '/api/v1/admin/plans',
    COUPONS: '/api/v1/admin/coupons',
    SUB_ADMINS: '/api/v1/admin/sub-admins',
    ROLES: '/api/v1/admin/roles',
    NOTIFICATIONS: '/api/v1/admin/notifications',
    SETTINGS: '/api/v1/admin/settings',
    SUPPORT_TICKETS: '/api/v1/admin/support/tickets',
    SUPPORT_UNREAD_COUNT: '/api/v1/admin/support/tickets/unread-count',
  },
} as const;
